### ISSUE TITLE
"python tf-minimal.py" not working

### ISSUE THREAD

**Issue by gkorland** [lantiga/RedisTF#13]
```
$ python tf-minimal.py 
Traceback (most recent call last):
  File "tf-minimal.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
```

**Comment by gkorland** [comment]
Installing TF helped but it's not part of the dependency

```
pip install --upgrade tensorflow
```

**Comment by lantiga** [comment]
You're right, I'll add this to the `README`. I don't think we can include it in `get_deps.sh`, since different setups will install TF differently, e.g. virtualenv vs conda, etc.

**Comment by lantiga** [comment]
Closing this for now, @gkorland feel free to reopen
