### ISSUE TITLE
Please create a new branch. ->  tensorFlow r1.2

### ISSUE THREAD

**Issue by ppeeou** [lantiga/RedisTF#3]
The codes in the current master branch are compatible with versions below tensorflow 1.0.
Could you please allow me to try to write the contents of tf_r1.2 branch currently being written to tensorflow 1.0 or later version?

**Comment by lantiga** [comment]
Hi @ppeeou, absolutely. I just created a tf_r1.2 branch at the current master tip. Can you redirect your PR to that branch?
Thank you!
